### ISSUE TITLE
[BUG] Specifications referring to IEC 61987 when we only have a data specification for IEC 61360

### ISSUE THREAD

**Issue by WelliSolutions** [admin-shell-io/aas-specs-iec61360#18] opened 2024-03-18 21:17 UTC
**Describe the bug**
This specification defines the id of IEC 61630 (electric/electronic components) properties, value lists and values as `https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIec61360/3/0`.

However, there are several documents using properties of IEC 61987 (process automation), e.g.
* IDTA-02013-1-0_Submodel_Reliability.pdf (8 hits)
* IDTA-02003-1-2_Submodel_TechnicalData.pdf (3 hits)
* IDTA-02002-1-0_Submodel_ContactInformation.pdf (2 hits)
* IDTA-02014-1-0_Submodel_FunctionalSafety.pdf (8 hits)
* IDTA-02006-2-0_Submodel_Digital-Nameplate.pdf (62 hits)

I don't feel comfortable linking to IEC 61987 properties from the global reference `https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIec61360/3/0`

**Where**
This specification, IDTA-01002-a-3-0, chapter 6.1, page 21
e.g. IDTA-02013-1-0, chapter 2.3, page 10
e.g. IDTA-02003-1-2, table 4, page 13
e.g. IDTA-02002-1-0, chapter 1.3, page 8 (just refers to the CDD)
e.g. IDTA-02014-1-0, chapter 2.3, page 10
e.g. IDTA-02006-2-0, chapter 3.1, page 9

**Screenshots**
None.

**Additional context**
I was trying to create a ConceptDescription in Package Explorer. In Package Explorer, I can easily create an IEC 61360 property. There's a button in the UI and it generates a nice external reference to `http://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360/3/0`. It does not provide capabilities for IEC 61987.

![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/c4a6dcb9-5814-4bd9-ac19-e72eb1984580)

**Comment by BirgitBoss** [comment] 2024-04-03 13:28
AAS allows to reuse any semantic concepts as long as they do have a unique ID. Part 3a is a data specification following IEC 61360 with respect to required attributes etc.  It is about syntax and not about content. 

It does not imply in any way that only IEC CDD properties can be used in Submodel Templates as you point out: this is not a contradiction to the specification.

AAS would allow to define additional data specifications for other standards if needed.

removed Bug label because it is not a bug to comply to the standard the data specification is designed for.

**Comment by BirgitBoss** [comment] 2024-07-19 15:24
For my understanding it does not affect the specification. This is why I close the issue.
Please feel free to reopen the issue if I missed something.

**Closed by BirgitBoss** 2024-07-19 15:24 UTC
Labels: invalid
